### PR TITLE
tag image with git commit hash as version

### PR DESCRIPTION
**Pull request by Danilosimoes**

### CODE REVIEW

**Comment by Danilosimoes** [comment]
image

Help me, please!

I don't know if it's correct.

**Comment by robsonoduarte** [comment]
@Danilosimoes the ideia is use the [Makefile](https://www.google.com/search?channel=fs&client=ubuntu-sn&q=makefile) to do this tasks:
image

using the makefile is more flexible instead  using the`buil.gradle`, with make file we can execute all shell commands and scripts.

**Comment by robsonoduarte** [comment]
the patch:
image
image

**Comment by Danilosimoes** [comment]
image

image

**Review by robsonoduarte — APPROVED** [review]
:muscle:

**Pull request merged**
