### PR TITLE
sonarqube and sonarcloud integration

### PR DESCRIPTION
**Pull request by Danilosimoes**
sonarqube and sonarcloud integration

### CODE REVIEW

**Comment by Danilosimoes** [comment]
The SONAR_TOKEN is not found, and we need SONAR_HOST. What do we do?

image

**Comment by Danilosimoes** [comment]
We need Public IP from virtual machine?

**Review by robsonoduarte — APPROVED** [review]
great job :muscle:

**Comment by Danilosimoes** [comment]
come onnnn

**Pull request merged**
