### PR TITLE
update to java 20

### PR DESCRIPTION
**Pull request by Danilosimoes**

### CODE REVIEW

**Comment by Danilosimoes** [comment]
I'm trying to turn java setup to 20, but any thing is wrong. Cause gradle 8.1 version doesn't work and i'm not getting to close this task.

need i to change de gradle version to 8.1? 
i was reading about it and i'd need to do it, but don´t work.


Can you help me?
give me the "stone path"

**Comment by robsonoduarte** [comment]
@Danilosimoes only change the version of gradle [here](https://github.com/robsonoduarte/u-vocab-api/blob/4a35785f17ef51113189bd43e29d9888d97e63fd/gradle/wrapper/gradle-wrapper.properties#L3), then the magic will be happen :magic_wand: 

P.S: we need change the java version in ghaction pipeline to. :eyeglasses:

**Comment by Danilosimoes** [comment]
I had change, but doesn't work and now again.
image

**Comment by robsonoduarte** [comment]
try change [here](https://github.com/robsonoduarte/u-vocab-api/blob/4a35785f17ef51113189bd43e29d9888d97e63fd/build.gradle#L10) to

**Comment by Danilosimoes** [comment]
I did it
image

**Comment by robsonoduarte** [comment]
[here](https://github.com/robsonoduarte/u-vocab-api/blob/4a35785f17ef51113189bd43e29d9888d97e63fd/.github/workflows/actions.yml#L19) to

image

**Comment by Danilosimoes** [comment]
C'Mon!!!!
It's workkk!!

**Review by robsonoduarte — APPROVED** [review]
great job ! :muscle:

**Pull request merged**
